### ISSUE TITLE
Tips about using git.

### ISSUE THREAD

**Issue by xiaoyu2006** [OI-Master/calc#2]
I don't really know if you can use `git` but it ***is*** able to upload the whole code base to GitHub. Maybe you can install a local [`git`](https://git-scm.com/) client and learn how to use it.

**Comment by OI-Master** [comment]
But the code is really large, and Git transmission is slow. 
I've actually been thinking about Git, but in the end, the code didn't go up.

**Comment by xiaoyu2006** [comment]
Maybe you can try this: https://github.com/chenxuhua/issues-blog/issues/3
